version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pastel24h_app
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
    networks:
      - pastel24h-network

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: pastel24h_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - pastel24h-network

networks:
  pastel24h-network:
    driver: bridge